### ISSUE TITLE
plugin réservation suppression automatique des évéments

### ISSUE THREAD

**Issue by flutter-painter** [paheko/paheko-plugins#1]
Bonjour,
Désolé d'ouvrir l'issue ici, mais je ne comprends pas comment la poster sur sur fossil https://fossil.kd2.org/paheko-plugins/index
ou sur le forum d'entraide : https://paheko.cloud/entraide
Le plugin événement ne stipule pas dans la documentation que : "les inscriptions passées (plus d'un mois) sont automatiquement supprimées."
Il s'agit d'une note en bas du tableau de l'onglet inscriptions.
Le suivi de la participation est une information clé pour notre association.
Pourquoi ne pas préciser cette contrainte de façon plus visible ?
Serait-il possible de mettre un paramètre pour désactiver cette suppression automatique ?
Je ne comprends pas à quoi sert ce trigger de suppression, le volume de données est trivial, même au format json.

**Comment by bohwaz** [comment]
Réponse faite à ton mail.
